@echo off
rem batch file for running a simple Java application generated by Coco - CSC 301 2004
rem you may need to set CLASSPATH
rem set CLASSPATH=.
if "%1" == "" goto missing
java %1.%1 %2 %3 %4 %5 %6 %7
goto stop
:missing
echo no application specified - use crun Grammar InputFile [-l [other directives]]
:stop
