@echo off
rem batch file for running a simple Parva (Java) compiler generated by Coco
rem you may need to set CLASSPATH
rem set CLASSPATH=.
java Parva.Parva %1 %2 %3 %4 %5
goto stop
:missing
echo no application specified - use Parva InputFile [-l [other directives]]
:stop
